import 'package:flutter/foundation.dart';
import 'package:nexqloud/features/main/models/server_model.dart';

class ServerDataProvider with ChangeNotifier {
  List<ServerModel> _data = <ServerModel>[];
  int totalActiveServers = 545;

  List<ServerModel> get data => _data;

  void setData() {
    _data = <ServerModel>[
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.87,
        region: 'US-E1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 37.7749,
        longitude: -122.4194,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'NA-US1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 41.8781,
        longitude: -87.6298,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.80,
        region: 'NA-US2',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 34.0522,
        longitude: -118.2437,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.10,
        region: 'NA-CA1',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 45.5017,
        longitude: -73.5673,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.91,
        region: 'US-W1',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 34.0522,
        longitude: -118.2437,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.11,
        region: 'CA-E2',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 43.6532,
        longitude: -79.3832,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.03,
        region: 'MX-W1',
        cores: 64,
        memory: 128,
        country: 'Mexico',
        latitude: 20.6597,
        longitude: -103.3496,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.87,
        region: 'US-E1',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 40.7128,
        longitude: -74.0060,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'US-W1',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 34.0522,
        longitude: -118.2437,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'CA-E1',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 43.65107,
        longitude: -79.347015,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'MX-W1',
        cores: 64,
        memory: 128,
        country: 'Mexico',
        latitude: 20.6597,
        longitude: -103.3496,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.43,
        region: 'US-SE1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 33.7490,
        longitude: -84.3880,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.65,
        region: 'US-E1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 40.7128,
        longitude: -74.0060,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'US-SE1',
        cores: 16,
        memory: 32,
        country: 'United States',
        latitude: 25.7617,
        longitude: -80.1918,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'US-SW1',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 32.7767,
        longitude: -96.7970,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'US-NW1',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 47.6062,
        longitude: -122.3321,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.01,
        region: 'US-C1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 41.8781,
        longitude: -87.6298,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'US-NE1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 42.3601,
        longitude: -71.0589,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'US-SE2',
        cores: 16,
        memory: 32,
        country: 'United States',
        latitude: 33.7490,
        longitude: -84.3880,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'US-SW2',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 33.4484,
        longitude: -112.0740,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.89,
        region: 'CA-E1',
        cores: 128,
        memory: 256,
        country: 'Canada',
        latitude: 45.5017,
        longitude: -73.5673,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.93,
        region: 'CA-W1',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 49.2827,
        longitude: -123.1207,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.56,
        region: 'CA-W2',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 53.5461,
        longitude: -113.4938,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'MX-E1',
        cores: 64,
        memory: 128,
        country: 'Mexico',
        latitude: 19.4326,
        longitude: -99.1332,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'MX-N1',
        cores: 32,
        memory: 64,
        country: 'Mexico',
        latitude: 25.6866,
        longitude: -100.3161,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.71,
        region: 'US-NW2',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 40.7608,
        longitude: -111.8910,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.49,
        region: 'US-S1',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 29.7604,
        longitude: -95.3698,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.50,
        region: 'NA-MX1',
        cores: 32,
        memory: 64,
        country: 'Mexico',
        latitude: 19.4326,
        longitude: -99.1332,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.19,
        region: 'US-C2',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 39.7392,
        longitude: -104.9903,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.02,
        region: 'US-NW3',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 45.5122,
        longitude: -122.6587,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.76,
        region: 'US-NC1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 44.9778,
        longitude: -93.2650,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'US-SE3',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 36.8508,
        longitude: -76.2859,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.81,
        region: 'US-W2',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 32.7157,
        longitude: -117.1611,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.47,
        region: 'CA-C1',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 49.8951,
        longitude: -97.1384,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.91,
        region: 'US-SE4',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 28.5383,
        longitude: -81.3792,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'US-W3',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 36.1699,
        longitude: -115.1398,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.98,
        region: 'US-MW1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 39.7684,
        longitude: -86.1581,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'US-NC2',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 42.3314,
        longitude: -83.0458,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'US-NC3',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 41.4993,
        longitude: -81.6944,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.87,
        region: 'US-NE2',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 42.8864,
        longitude: -78.8784,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'US-SE5',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 35.7796,
        longitude: -78.6382,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.67,
        region: 'US-MW2',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 41.2565,
        longitude: -95.9345,
        continent: 'North America',
      ),
      /////////////
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.76,
        region: 'BR-E1',
        cores: 16,
        memory: 32,
        country: 'Brazil',
        latitude: -14.235004,
        longitude: -51.92528,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'BR-S1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -22.9068,
        longitude: -43.1729,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.89,
        region: 'AR-C1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -31.4201,
        longitude: -64.1888,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.87,
        region: 'BR-S1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -22.9068,
        longitude: -43.1729,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'AR-C1',
        cores: 64,
        memory: 128,
        country: 'Argentina',
        latitude: -34.6037,
        longitude: -58.3816,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'CL-E1',
        cores: 64,
        memory: 128,
        country: 'Chile',
        latitude: -33.4489,
        longitude: -70.6693,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'CO-C1',
        cores: 32,
        memory: 64,
        country: 'Colombia',
        latitude: 4.7110,
        longitude: -74.0721,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.97,
        region: 'PE-W1',
        cores: 32,
        memory: 64,
        country: 'Peru',
        latitude: -12.0464,
        longitude: -77.0428,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.88,
        region: 'BR-S1',
        cores: 128,
        memory: 256,
        country: 'Brazil',
        latitude: -23.5505,
        longitude: -46.6333,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.03,
        region: 'BR-C1',
        cores: 64,
        memory: 128,
        country: 'Brazil',
        latitude: -19.9167,
        longitude: -43.9345,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.76,
        region: 'AR-E1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -34.6037,
        longitude: -58.3816,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.99,
        region: 'CO-C1',
        cores: 32,
        memory: 64,
        country: 'Colombia',
        latitude: 4.7110,
        longitude: -74.0721,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.87,
        region: 'CL-W1',
        cores: 64,
        memory: 128,
        country: 'Chile',
        latitude: -33.4489,
        longitude: -70.6693,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.88,
        region: 'PE-C1',
        cores: 32,
        memory: 64,
        country: 'Peru',
        latitude: -12.0464,
        longitude: -77.0428,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.98,
        region: 'VE-N1',
        cores: 64,
        memory: 128,
        country: 'Venezuela',
        latitude: 10.4806,
        longitude: -66.9036,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'UY-S1',
        cores: 32,
        memory: 64,
        country: 'Uruguay',
        latitude: -34.9011,
        longitude: -56.1645,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'BR-S2',
        cores: 64,
        memory: 128,
        country: 'Brazil',
        latitude: -25.4284,
        longitude: -49.2733,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.56,
        region: 'AR-C2',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -31.6234,
        longitude: -60.7003,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'CL-N1',
        cores: 64,
        memory: 128,
        country: 'Chile',
        latitude: -33.0245,
        longitude: -71.5518,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'SA-BR1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -22.9068,
        longitude: -43.1729,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.65,
        region: 'SA-AR1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -34.6037,
        longitude: -58.3816,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.60,
        region: 'SA-CL1',
        cores: 32,
        memory: 64,
        country: 'Chile',
        latitude: -33.4489,
        longitude: -70.6693,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.90,
        region: 'SA-PE1',
        cores: 32,
        memory: 64,
        country: 'Peru',
        latitude: -12.0432,
        longitude: -77.0283,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.30,
        region: 'SA-CO1',
        cores: 32,
        memory: 64,
        country: 'Colombia',
        latitude: 4.7100,
        longitude: -74.0721,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'BR-N1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -3.7172,
        longitude: -38.5434,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.31,
        region: 'AR-S1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -32.9468,
        longitude: -60.6393,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.57,
        region: 'CL-N2',
        cores: 64,
        memory: 128,
        country: 'Chile',
        latitude: -23.6500,
        longitude: -70.4000,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.24,
        region: 'CO-N1',
        cores: 64,
        memory: 128,
        country: 'Colombia',
        latitude: 6.2442,
        longitude: -75.5812,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.10,
        region: 'PE-N1',
        cores: 32,
        memory: 64,
        country: 'Peru',
        latitude: -8.1091,
        longitude: -79.0215,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.93,
        region: 'VE-W1',
        cores: 64,
        memory: 128,
        country: 'Venezuela',
        latitude: 10.6317,
        longitude: -71.6406,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.35,
        region: 'UY-E1',
        cores: 32,
        memory: 64,
        country: 'Uruguay',
        latitude: -34.8613,
        longitude: -56.1994,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.27,
        region: 'BR-A1',
        cores: 64,
        memory: 128,
        country: 'Brazil',
        latitude: -3.1190,
        longitude: -60.0217,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.91,
        region: 'AR-E2',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -31.6234,
        longitude: -60.7003,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.16,
        region: 'CO-S1',
        cores: 32,
        memory: 64,
        country: 'Colombia',
        latitude: 3.4516,
        longitude: -76.5320,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.08,
        region: 'CL-S1',
        cores: 32,
        memory: 64,
        country: 'Chile',
        latitude: -41.4717,
        longitude: -72.9411,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.32,
        region: 'PE-S1',
        cores: 64,
        memory: 128,
        country: 'Peru',
        latitude: -16.4090,
        longitude: -71.5375,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.22,
        region: 'BR-W1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -9.9747,
        longitude: -67.8243,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.94,
        region: 'VE-W2',
        cores: 32,
        memory: 64,
        country: 'Venezuela',
        latitude: 8.5986,
        longitude: -71.1561,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.29,
        region: 'UY-N1',
        cores: 32,
        memory: 64,
        country: 'Uruguay',
        latitude: -30.9054,
        longitude: -55.5508,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.04,
        region: 'CO-N2',
        cores: 32,
        memory: 64,
        country: 'Colombia',
        latitude: 7.1193,
        longitude: -73.1227,
        continent: 'South America',
      ),

      ///////////
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.85,
        region: 'RU-E1',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 55.755826,
        longitude: 37.6173,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'DE-N1',
        cores: 64,
        memory: 128,
        country: 'Germany',
        latitude: 52.5200,
        longitude: 13.4050,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'RU-W1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 59.9343,
        longitude: 30.3351,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'UK-N1',
        cores: 64,
        memory: 128,
        country: 'United Kingdom',
        latitude: 53.4808,
        longitude: -2.2426,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'FR-S1',
        cores: 64,
        memory: 128,
        country: 'France',
        latitude: 43.2965,
        longitude: 5.3698,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'IT-N1',
        cores: 64,
        memory: 128,
        country: 'Italy',
        latitude: 45.4642,
        longitude: 9.1900,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'ES-E2',
        cores: 32,
        memory: 64,
        country: 'Spain',
        latitude: 41.3851,
        longitude: 2.1734,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.76,
        region: 'SE-W1',
        cores: 64,
        memory: 128,
        country: 'Sweden',
        latitude: 57.7089,
        longitude: 11.9746,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.54,
        region: 'NO-W1',
        cores: 32,
        memory: 64,
        country: 'Norway',
        latitude: 60.3913,
        longitude: 5.3221,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'FI-S1',
        cores: 64,
        memory: 128,
        country: 'Finland',
        latitude: 60.4518,
        longitude: 22.2666,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.32,
        region: 'DK-E1',
        cores: 32,
        memory: 64,
        country: 'Denmark',
        latitude: 56.1572,
        longitude: 10.2107,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'CH-W1',
        cores: 64,
        memory: 128,
        country: 'Switzerland',
        latitude: 46.2044,
        longitude: 6.1432,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'AT-S1',
        cores: 32,
        memory: 64,
        country: 'Austria',
        latitude: 47.0707,
        longitude: 15.4395,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'PL-SW1',
        cores: 64,
        memory: 128,
        country: 'Poland',
        latitude: 51.1079,
        longitude: 17.0385,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.01,
        region: 'CZ-SE1',
        cores: 32,
        memory: 64,
        country: 'Czech Republic',
        latitude: 49.1951,
        longitude: 16.6068,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'HU-E1',
        cores: 64,
        memory: 128,
        country: 'Hungary',
        latitude: 47.5316,
        longitude: 21.6273,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.98,
        region: 'RO-W1',
        cores: 32,
        memory: 64,
        country: 'Romania',
        latitude: 45.7489,
        longitude: 21.2087,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'BG-E1',
        cores: 64,
        memory: 128,
        country: 'Bulgaria',
        latitude: 43.2141,
        longitude: 27.9147,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'DE-N1',
        cores: 64,
        memory: 128,
        country: 'Germany',
        latitude: 52.5200,
        longitude: 13.4050,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'UK-E1',
        cores: 64,
        memory: 128,
        country: 'United Kingdom',
        latitude: 51.5074,
        longitude: -0.1278,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'FR-N1',
        cores: 64,
        memory: 128,
        country: 'France',
        latitude: 48.8566,
        longitude: 2.3522,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'IT-C1',
        cores: 32,
        memory: 64,
        country: 'Italy',
        latitude: 41.9028,
        longitude: 12.4964,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'RU-W1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 55.7558,
        longitude: 37.6173,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'EU-UK1',
        cores: 32,
        memory: 64,
        country: 'United Kingdom',
        latitude: 51.5074,
        longitude: -0.1278,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'EU-FR1',
        cores: 32,
        memory: 64,
        country: 'France',
        latitude: 48.8567,
        longitude: 2.351,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'EU-DE1',
        cores: 32,
        memory: 64,
        country: 'Germany',
        latitude: 52.5244,
        longitude: 13.4105,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'EU-NL1',
        cores: 32,
        memory: 64,
        country: 'Netherlands',
        latitude: 52.3702,
        longitude: 4.8952,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.90,
        region: 'EU-DE1',
        cores: 32,
        memory: 64,
        country: 'Germany',
        latitude: 48.8567,
        longitude: 2.3510,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.95,
        region: 'EU-TR1',
        cores: 32,
        memory: 64,
        country: 'Turkey',
        latitude: 41.0082,
        longitude: 28.9744,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.50,
        region: 'EU-DK1',
        cores: 32,
        memory: 64,
        country: 'Denmark',
        latitude: 55.6761,
        longitude: 12.5683,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.20,
        region: 'EU-SE1',
        cores: 32,
        memory: 64,
        country: 'Sweden',
        latitude: 59.3293,
        longitude: 18.0686,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.60,
        region: 'EU-ES1',
        cores: 32,
        memory: 64,
        country: 'Spain',
        latitude: 40.4168,
        longitude: -3.7038,
        continent: 'Europe',
      ),
      // ///////////
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'AU-E2',
        cores: 16,
        memory: 32,
        country: 'Australia',
        latitude: -33.8688,
        longitude: 151.2093,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'NZ-N1',
        cores: 64,
        memory: 128,
        country: 'New Zealand',
        latitude: -41.2865,
        longitude: 174.7762,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'AU-E1',
        cores: 128,
        memory: 256,
        country: 'Australia',
        latitude: -33.8688,
        longitude: 151.2093,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.21,
        region: 'NZ-N1',
        cores: 64,
        memory: 128,
        country: 'New Zealand',
        latitude: -36.8485,
        longitude: 174.7633,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99,
        region: 'OC-AU1',
        cores: 32,
        memory: 64,
        country: 'Australia',
        latitude: -33.8688,
        longitude: 151.2093,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.40,
        region: 'OC-NZ1',
        cores: 32,
        memory: 64,
        country: 'New Zealand',
        latitude: -41.2865,
        longitude: 174.7762,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.71,
        region: 'AU-E3',
        cores: 64,
        memory: 128,
        country: 'Australia',
        latitude: -37.8136,
        longitude: 144.9631, // Melbourne
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.62,
        region: 'NZ-N2',
        cores: 32,
        memory: 64,
        country: 'New Zealand',
        latitude: -43.5321,
        longitude: 172.6362, // Christchurch
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.80,
        region: 'AU-W1',
        cores: 32,
        memory: 64,
        country: 'Australia',
        latitude: -31.9505,
        longitude: 115.8605, // Perth
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.58,
        region: 'NZ-N3',
        cores: 16,
        memory: 32,
        country: 'New Zealand',
        latitude: -37.7870,
        longitude: 175.2793, // Hamilton
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.74,
        region: 'AU-N1',
        cores: 128,
        memory: 256,
        country: 'Australia',
        latitude: -27.4698,
        longitude: 153.0251, // Brisbane
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.65,
        region: 'FJ-N1',
        cores: 16,
        memory: 32,
        country: 'Fiji',
        latitude: -18.1248,
        longitude: 178.4501, // Suva, Fiji
        continent: 'Oceania',
      ),

      /////////////
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.05,
        region: 'IN-W1',
        cores: 64,
        memory: 128,
        country: 'India',
        latitude: 19.0760,
        longitude: 72.8777,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.93,
        region: 'CN-E2',
        cores: 128,
        memory: 256,
        country: 'China',
        latitude: 31.2304,
        longitude: 121.4737,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.81,
        region: 'JP-W1',
        cores: 64,
        memory: 128,
        country: 'Japan',
        latitude: 34.6937,
        longitude: 135.5023,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'TR-C1',
        cores: 32,
        memory: 64,
        country: 'Turkey',
        latitude: 39.9334,
        longitude: 32.8597,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.98,
        region: 'SA-W1',
        cores: 64,
        memory: 128,
        country: 'Saudi Arabia',
        latitude: 21.2854,
        longitude: 39.2376,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.87,
        region: 'IR-NE1',
        cores: 32,
        memory: 64,
        country: 'Iran',
        latitude: 36.2605,
        longitude: 59.6168,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'TH-N1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 18.7883,
        longitude: 98.9853,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'RU-C1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 56.8389,
        longitude: 60.6057,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.89,
        region: 'CN-SW1',
        cores: 64,
        memory: 128,
        country: 'China',
        latitude: 29.4316,
        longitude: 106.9123,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'RU-SB1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 54.9885,
        longitude: 73.3242,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'JP-E1',
        cores: 64,
        memory: 128,
        country: 'Japan',
        latitude: 35.6762,
        longitude: 139.6503,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.54,
        region: 'CN-N1',
        cores: 128,
        memory: 256,
        country: 'China',
        latitude: 39.9042,
        longitude: 116.4074,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'IN-N1',
        cores: 64,
        memory: 128,
        country: 'India',
        latitude: 28.7041,
        longitude: 77.1025,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.87,
        region: 'KR-E1',
        cores: 32,
        memory: 64,
        country: 'South Korea',
        latitude: 37.5665,
        longitude: 126.9780,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.23,
        region: 'TH-E1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 13.7563,
        longitude: 100.5018,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'AS-TH1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 13.7563,
        longitude: 100.5018,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'AS-TW1',
        cores: 32,
        memory: 64,
        country: 'Taiwan',
        latitude: 25.04,
        longitude: 121.44,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'AS-HK1',
        cores: 32,
        memory: 64,
        country: 'Hong Kong',
        latitude: 22.3964,
        longitude: 114.1095,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'AS-ID1',
        cores: 32,
        memory: 64,
        country: 'Indonesia',
        latitude: -6.2146,
        longitude: 106.8451,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'AS-JP1',
        cores: 32,
        memory: 64,
        country: 'Japan',
        latitude: 35.6895,
        longitude: 139.767,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'AS-KR1',
        cores: 32,
        memory: 64,
        country: 'South Korea',
        latitude: 37.5665,
        longitude: 126.9779,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'AS-SG1',
        cores: 32,
        memory: 64,
        country: 'Singapore',
        latitude: 1.3521,
        longitude: 103.8198,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.75,
        region: 'AS-TH1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 13.7563,
        longitude: 100.5018,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.85,
        region: 'AS-IN1',
        cores: 32,
        memory: 64,
        country: 'India',
        latitude: 28.7041,
        longitude: 77.1025,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.70,
        region: 'AS-JP1',
        cores: 32,
        memory: 64,
        country: 'Japan',
        latitude: 35.6895,
        longitude: 139.7670,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.30,
        region: 'AS-TH1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 13.7563,
        longitude: 100.5018,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.70,
        region: 'AS-HK1',
        cores: 32,
        memory: 64,
        country: 'Hong Kong',
        latitude: 22.3964,
        longitude: 114.1095,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.55,
        region: 'PH-N1',
        cores: 32,
        memory: 64,
        country: 'Philippines',
        latitude: 14.5995,
        longitude: 120.9842,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.73,
        region: 'VN-N1',
        cores: 32,
        memory: 128,
        country: 'Vietnam',
        latitude: 21.0285,
        longitude: 105.8542,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.87,
        region: 'MY-S1',
        cores: 64,
        memory: 128,
        country: 'Malaysia',
        latitude: 3.1390,
        longitude: 101.6869,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.33,
        region: 'BD-E1',
        cores: 32,
        memory: 64,
        country: 'Bangladesh',
        latitude: 23.8103,
        longitude: 90.4125,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'PK-W1',
        cores: 64,
        memory: 128,
        country: 'Pakistan',
        latitude: 31.5497,
        longitude: 74.3436,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.19,
        region: 'MM-N1',
        cores: 32,
        memory: 64,
        country: 'Myanmar',
        latitude: 16.8661,
        longitude: 96.1951,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.61,
        region: 'ID-S1',
        cores: 64,
        memory: 128,
        country: 'Indonesia',
        latitude: -8.6705,
        longitude: 115.2126,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.50,
        region: 'NP-N1',
        cores: 32,
        memory: 64,
        country: 'Nepal',
        latitude: 27.7172,
        longitude: 85.3240,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.90,
        region: 'SG-W1',
        cores: 128,
        memory: 256,
        country: 'Singapore',
        latitude: 1.3521,
        longitude: 103.8198,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.89,
        region: 'TW-N1',
        cores: 64,
        memory: 128,
        country: 'Taiwan',
        latitude: 25.0330,
        longitude: 121.5654,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.63,
        region: 'KH-N1',
        cores: 32,
        memory: 64,
        country: 'Cambodia',
        latitude: 11.5564,
        longitude: 104.9282,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.48,
        region: 'LK-S1',
        cores: 32,
        memory: 64,
        country: 'Sri Lanka',
        latitude: 6.9271,
        longitude: 79.8612,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.29,
        region: 'UZ-N1',
        cores: 64,
        memory: 128,
        country: 'Uzbekistan',
        latitude: 41.2995,
        longitude: 69.2401,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.67,
        region: 'KZ-S1',
        cores: 128,
        memory: 256,
        country: 'Kazakhstan',
        latitude: 43.2220,
        longitude: 76.8512,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.42,
        region: 'MN-E1',
        cores: 64,
        memory: 128,
        country: 'Mongolia',
        latitude: 47.8864,
        longitude: 106.9057,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.72,
        region: 'KZ-N1',
        cores: 64,
        memory: 128,
        country: 'Kazakhstan',
        latitude: 51.1694,
        longitude: 71.4491,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.61,
        region: 'RU-E1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 53.7281,
        longitude: 91.4419,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'RU-W1',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 55.0084,
        longitude: 82.9357,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.57,
        region: 'RU-E2',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 52.2871,
        longitude: 104.2810,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.88,
        region: 'CN-NW1',
        cores: 128,
        memory: 256,
        country: 'China',
        latitude: 43.8256,
        longitude: 87.6168,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.74,
        region: 'MN-N1',
        cores: 64,
        memory: 128,
        country: 'Mongolia',
        latitude: 44.8232,
        longitude: 110.2869,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.32,
        region: 'RU-C2',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 56.1168,
        longitude: 47.2513,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.51,
        region: 'MN-C1',
        cores: 32,
        memory: 64,
        country: 'Mongolia',
        latitude: 46.0702,
        longitude: 111.9734,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.60,
        region: 'RU-FE1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 48.4808,
        longitude: 135.0838,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.77,
        region: 'CN-N2',
        cores: 64,
        memory: 128,
        country: 'China',
        latitude: 50.2501,
        longitude: 127.5350,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.48,
        region: 'KZ-S2',
        cores: 64,
        memory: 128,
        country: 'Kazakhstan',
        latitude: 49.2144,
        longitude: 71.9666,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.30,
        region: 'RU-W2',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 48.3558,
        longitude: 92.8681,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.69,
        region: 'CN-NE1',
        cores: 128,
        memory: 256,
        country: 'China',
        latitude: 45.8038,
        longitude: 126.5349,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.54,
        region: 'MN-E1',
        cores: 32,
        memory: 64,
        country: 'Mongolia',
        latitude: 48.3794,
        longitude: 99.0239,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.66,
        region: 'RU-C3',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 56.4846,
        longitude: 84.9476,
        continent: 'Asia',
      ),

      /////////////
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.40,
        region: 'AF-KE1',
        cores: 32,
        memory: 64,
        country: 'Kenya',
        latitude: -1.2921,
        longitude: 36.8219,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.21,
        region: 'ZA-W1',
        cores: 32,
        memory: 64,
        country: 'South Africa',
        latitude: -33.9249,
        longitude: 18.4241,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.01,
        region: 'EG-N1',
        cores: 64,
        memory: 128,
        country: 'Egypt',
        latitude: 31.2001,
        longitude: 29.9187,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'ZA-W1',
        cores: 64,
        memory: 128,
        country: 'South Africa',
        latitude: -33.9249,
        longitude: 18.4241,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'NG-E1',
        cores: 32,
        memory: 64,
        country: 'Nigeria',
        latitude: 6.5244,
        longitude: 3.3792,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.99,
        region: 'EG-N1',
        cores: 64,
        memory: 128,
        country: 'Egypt',
        latitude: 30.0444,
        longitude: 31.2357,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.56,
        region: 'AF-ZA1',
        cores: 32,
        memory: 64,
        country: 'South Africa',
        latitude: -33.9249,
        longitude: 18.4241,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.12,
        region: 'AF-EG1',
        cores: 32,
        memory: 64,
        country: 'Egypt',
        latitude: 30.05,
        longitude: 31.25,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.80,
        region: 'AF-NG1',
        cores: 32,
        memory: 64,
        country: 'Nigeria',
        latitude: 6.4551,
        longitude: 3.3947,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.22,
        region: 'AF-RW1',
        cores: 32,
        memory: 64,
        country: 'Rwanda',
        latitude: -1.9441,
        longitude: 30.0619,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.35,
        region: 'AF-ET1',
        cores: 64,
        memory: 128,
        country: 'Ethiopia',
        latitude: 9.0371,
        longitude: 38.7613,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.28,
        region: 'AF-TZ1',
        cores: 32,
        memory: 64,
        country: 'Tanzania',
        latitude: -6.7924,
        longitude: 39.2083,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.14,
        region: 'AF-SN1',
        cores: 64,
        memory: 128,
        country: 'Senegal',
        latitude: 14.6928,
        longitude: -17.4467,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.06,
        region: 'AF-CI1',
        cores: 32,
        memory: 64,
        country: "Cote d'Ivoire",
        latitude: 5.3097,
        longitude: -4.0127,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.43,
        region: 'AF-GH1',
        cores: 64,
        memory: 128,
        country: 'Ghana',
        latitude: 5.6037,
        longitude: -0.1870,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.19,
        region: 'AF-NG2',
        cores: 32,
        memory: 64,
        country: 'Nigeria',
        latitude: 12.0022,
        longitude: 8.5919,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 98.95,
        region: 'AF-MZ1',
        cores: 64,
        memory: 128,
        country: 'Mozambique',
        latitude: -25.9653,
        longitude: 32.5892,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.32,
        region: 'AF-NA1',
        cores: 32,
        memory: 64,
        country: 'Namibia',
        latitude: -22.5609,
        longitude: 17.0658,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.25,
        region: 'AF-ZM1',
        cores: 32,
        memory: 64,
        country: 'Zambia',
        latitude: -15.4160,
        longitude: 28.2814,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.18,
        region: 'AF-TD1',
        cores: 32,
        memory: 64,
        country: 'Chad',
        latitude: 12.1348,
        longitude: 15.0557,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.09,
        region: 'AF-DJ1',
        cores: 32,
        memory: 64,
        country: 'Djibouti',
        latitude: 11.5880,
        longitude: 43.1456,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.02,
        region: 'AF-GA1',
        cores: 32,
        memory: 64,
        country: 'Gabon',
        latitude: 0.4162,
        longitude: 9.4673,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.33,
        region: 'AF-MD1',
        cores: 64,
        memory: 128,
        country: 'Madagascar',
        latitude: -18.8792,
        longitude: 47.5079,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.24,
        region: 'AF-ZM2',
        cores: 32,
        memory: 64,
        country: 'Zambia',
        latitude: -15.3875,
        longitude: 28.3238,
        continent: 'Africa',
      ),
      // Antarctica
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.98,
        region: 'AQ-S1',
        cores: 128,
        memory: 512,
        country: 'Antarctica',
        latitude: -77.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.92,
        region: 'AQ-S2',
        cores: 64,
        memory: 256,
        country: 'Antarctica',
        latitude: -75.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.91,
        region: 'AQ-S3',
        cores: 32,
        memory: 128,
        country: 'Antarctica',
        latitude: -72.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.85,
        region: 'AQ-S4',
        cores: 64,
        memory: 256,
        country: 'Antarctica',
        latitude: -71.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.76,
        region: 'AQ-S5',
        cores: 32,
        memory: 128,
        country: 'Antarctica',
        latitude: -87.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.82,
        region: 'AQ-S6',
        cores: 64,
        memory: 256,
        country: 'Antarctica',
        latitude: -82.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.73,
        region: 'AQ-S7',
        cores: 32,
        memory: 128,
        country: 'Antarctica',
        latitude: -85.8419,
        longitude: 166.6863,
        continent: 'Antarctica',
      ),
      // Corrected Antarctica latitudes and longitudes
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.98,
        region: 'AQ-S1',
        cores: 128,
        memory: 512,
        country: 'Antarctica',
        latitude: -77.8419,
        longitude: 166.6863, // McMurdo Station location
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.92,
        region: 'AQ-S2',
        cores: 64,
        memory: 256,
        country: 'Antarctica',
        latitude: -75.8419,
        longitude: 123.3947, // Near Dome A
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.91,
        region: 'AQ-S3',
        cores: 32,
        memory: 128,
        country: 'Antarctica',
        latitude: -72.8419,
        longitude: 2.5359, // Near Troll Station
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.85,
        region: 'AQ-S4',
        cores: 64,
        memory: 256,
        country: 'Antarctica',
        latitude: -71.8419,
        longitude: 11.7333, // Near Neumayer-Station
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.76,
        region: 'AQ-S5',
        cores: 32,
        memory: 128,
        country: 'Antarctica',
        latitude: -77.5,
        longitude: 163.6, // Ross Island
        continent: 'Antarctica',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.82,
        region: 'AQ-S6',
        cores: 64,
        memory: 256,
        country: 'Antarctica',
        latitude: -80.8419,
        longitude: 77.0625, // Lambert Glacier vicinity
        continent: 'Antarctica',
      ),

      // Greenland Servers
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'GL-S1',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 64.1835,
        longitude: -51.7216, // Nuuk
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.37,
        region: 'GL-N1',
        cores: 64,
        memory: 128,
        country: 'Greenland',
        latitude: 67.0167,
        longitude: -50.6867, // Sisimiut
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.15,
        region: 'GL-E1',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 70.6731,
        longitude: -52.1241, // Uummannaq
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.08,
        region: 'GL-W1',
        cores: 64,
        memory: 128,
        country: 'Greenland',
        latitude: 69.2462,
        longitude: -51.2167, // Kangerlussuaq
        continent: 'North America',
      ),

// Norway Servers
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.72,
        region: 'NO-S1',
        cores: 64,
        memory: 128,
        country: 'Norway',
        latitude: 59.9139,
        longitude: 10.7522, // Oslo
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.51,
        region: 'NO-W1',
        cores: 32,
        memory: 64,
        country: 'Norway',
        latitude: 60.3921,
        longitude: 5.3221, // Bergen
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.34,
        region: 'NO-N1',
        cores: 32,
        memory: 64,
        country: 'Norway',
        latitude: 63.4305,
        longitude: 10.3951, // Trondheim
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.28,
        region: 'NO-N2',
        cores: 64,
        memory: 128,
        country: 'Norway',
        latitude: 69.6492,
        longitude: 18.9553, // Tromsø
        continent: 'Europe',
      ),

// Canada Servers
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.85,
        region: 'CA-E1',
        cores: 128,
        memory: 256,
        country: 'Canada',
        latitude: 43.6511,
        longitude: -79.3837, // Toronto
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.61,
        region: 'CA-W1',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 49.2827,
        longitude: -123.1207, // Vancouver
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.42,
        region: 'CA-C1',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 45.4215,
        longitude: -75.6972, // Ottawa
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.30,
        region: 'CA-E2',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 45.5017,
        longitude: -73.5673, // Montreal
        continent: 'North America',
      ),

// Iceland Servers
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.64,
        region: 'IS-S1',
        cores: 64,
        memory: 128,
        country: 'Iceland',
        latitude: 64.1466,
        longitude: -21.9426, // Reykjavik
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.52,
        region: 'IS-N1',
        cores: 32,
        memory: 64,
        country: 'Iceland',
        latitude: 65.6823,
        longitude: -18.0892, // Akureyri
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.41,
        region: 'IS-W1',
        cores: 32,
        memory: 64,
        country: 'Iceland',
        latitude: 64.2510,
        longitude: -15.2108, // Höfn
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.33,
        region: 'IS-W2',
        cores: 64,
        memory: 128,
        country: 'Iceland',
        latitude: 66.0740,
        longitude: -23.1236, // Ísafjörður
        continent: 'Europe',
      ),

      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.75,
        region: 'RU-W1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 55.7558,
        longitude: 37.6173, // Moscow
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.64,
        region: 'RU-W2',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 59.9343,
        longitude: 30.3351, // Saint Petersburg
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.41,
        region: 'RU-C1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 55.8304,
        longitude: 49.0661, // Kazan
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.38,
        region: 'RU-S1',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 55.0084,
        longitude: 82.9357, // Novosibirsk
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.28,
        region: 'RU-E1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 48.4827,
        longitude: 135.0838, // Khabarovsk
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.21,
        region: 'RU-S2',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 52.2871,
        longitude: 104.2807, // Irkutsk
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.15,
        region: 'RU-S3',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 54.9893,
        longitude: 73.3682, // Omsk
        continent: 'Asia',
      ),

      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.78,
        region: 'CA-W2',
        cores: 128,
        memory: 256,
        country: 'Canada',
        latitude: 51.0447,
        longitude: -114.0719, // Calgary
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.66,
        region: 'CA-C2',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 49.8951,
        longitude: -97.1384, // Winnipeg
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.55,
        region: 'CA-W3',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 53.5461,
        longitude: -113.4938, // Edmonton
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.42,
        region: 'CA-E3',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 44.6488,
        longitude: -63.5752, // Halifax
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.30,
        region: 'CA-W4',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 49.2827,
        longitude: -123.1207, // Vancouver (Duplicate region, but unique server)
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.25,
        region: 'CA-E4',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 46.8139,
        longitude: -71.2082, // Quebec City
        continent: 'North America',
      ),

      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.54,
        region: 'GL-N2',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 76.5312,
        longitude: -68.7032, // Thule Air Base
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.46,
        region: 'GL-C1',
        cores: 64,
        memory: 128,
        country: 'Greenland',
        latitude: 69.2193,
        longitude: -51.0998, // Ilulissat
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.32,
        region: 'GL-W2',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 67.0081,
        longitude: -50.6899, // Kangaatsiaq
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.28,
        region: 'GL-N3',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 70.7890,
        longitude: -52.3270, // Narsarsuaq
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.11,
        region: 'GL-S2',
        cores: 64,
        memory: 128,
        country: 'Greenland',
        latitude: 60.7155,
        longitude: -46.0445, // Qaqortoq
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.25,
        region: 'RU-N1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 69.0739,
        longitude: 33.4151,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.28,
        region: 'RU-N4',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 70,
        longitude: 137,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.30,
        region: 'RU-N3',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 72.7769,
        longitude: 77.6121,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.52,
        region: 'RU-N5',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 65.9945,
        longitude: 57.6930,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.42,
        region: 'RU-E4',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 67.8533,
        longitude: 135.0338,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.36,
        region: 'RU-S4',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 66.4217,
        longitude: 112.0108,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.31,
        region: 'RU-S5',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 72.9967,
        longitude: 102.4938,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.28,
        region: 'RU-E5',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 62.0281,
        longitude: 129.7331,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.19,
        region: 'RU-N6',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 70.3431,
        longitude: 82.9172,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'GL-N5',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 74.1984,
        longitude: -20.5017,
        continent: 'North America',
      ),

      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.62,
        region: 'IS-C1',
        cores: 64,
        memory: 128,
        country: 'Iceland',
        latitude: 65,
        longitude: -18,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.51,
        region: 'NO-N3',
        cores: 64,
        memory: 128,
        country: 'Norway',
        latitude: 70.9828,
        longitude: 25.9765,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'SRV-84O70Q',
        uptime: 99.45,
        region: 'GL-N3',
        cores: 32,
        memory: 64,
        country: 'Greenland',
        latitude: 83.6500,
        longitude: -32.4500,
        continent: 'North America',
      ),
    ];
  }

  List<String> getContinentList() {
    return data.map((e) => e.continent).toSet().toList();
  }

  // find one server data from a continent
  ServerModel findContinentServer(String continent) {
    return data.firstWhere(
      (element) => element.continent == continent,
      orElse: () => ServerModel.empty(),
    );
  }

  List<String> getCountryList() {
    return data.map((e) => e.country).toSet().toList();
  }

  // find country based markers
  List<ServerModel> findCountry(String country) {
    return data.where((element) => element.country == country).toList();
  }

  List<String> getRegionList() {
    return data.map((e) => e.region).toSet().toList();
  }

  // find region based markers
  List<ServerModel> findRegion(String region) {
    return data.where((element) => element.region == region).toList();
  }

  // find countries in a continent
  List<String> findCountryInContinent(String continent) {
    return data
        .where((element) => element.continent == continent)
        .map((e) => e.country)
        .toSet()
        .toList();
  }
}
