import 'package:flutter/foundation.dart';
import 'package:nexqloud/features/main/models/server_model.dart';

class ServerDataProvider with ChangeNotifier {
  List<ServerModel> _data = <ServerModel>[];

  List<ServerModel> get data => _data;

  void setData() {
    _data = <ServerModel>[
      const ServerModel(
        serverName: 'NXQ-842-EEV',
        uptime: 99.87,
        region: 'US-E1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 37.7749,
        longitude: -122.4194,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'BRZ-452-QZA',
        uptime: 98.76,
        region: 'BR-E1',
        cores: 16,
        memory: 32,
        country: 'Brazil',
        latitude: -14.235004,
        longitude: -51.92528,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'RUS-576-NVS',
        uptime: 99.85,
        region: 'RU-E1',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 55.755826,
        longitude: 37.6173,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'US-577-LAX',
        uptime: 99.91,
        region: 'US-W1',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 34.0522,
        longitude: -118.2437,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'BR-578-RIO',
        uptime: 99.23,
        region: 'BR-S1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -22.9068,
        longitude: -43.1729,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'DE-579-BER',
        uptime: 99.78,
        region: 'DE-N1',
        cores: 64,
        memory: 128,
        country: 'Germany',
        latitude: 52.5200,
        longitude: 13.4050,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'AU-580-SYD',
        uptime: 99.67,
        region: 'AU-E2',
        cores: 16,
        memory: 32,
        country: 'Australia',
        latitude: -33.8688,
        longitude: 151.2093,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'IN-581-MUM',
        uptime: 99.05,
        region: 'IN-W1',
        cores: 64,
        memory: 128,
        country: 'India',
        latitude: 19.0760,
        longitude: 72.8777,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'RU-582-SPB',
        uptime: 99.45,
        region: 'RU-W1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 59.9343,
        longitude: 30.3351,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'UK-583-MAN',
        uptime: 99.56,
        region: 'UK-N1',
        cores: 64,
        memory: 128,
        country: 'United Kingdom',
        latitude: 53.4808,
        longitude: -2.2426,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'CN-584-SHA',
        uptime: 99.93,
        region: 'CN-E2',
        cores: 128,
        memory: 256,
        country: 'China',
        latitude: 31.2304,
        longitude: 121.4737,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'JP-585-OSA',
        uptime: 99.81,
        region: 'JP-W1',
        cores: 64,
        memory: 128,
        country: 'Japan',
        latitude: 34.6937,
        longitude: 135.5023,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'CA-586-TOR',
        uptime: 99.11,
        region: 'CA-E2',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 43.6532,
        longitude: -79.3832,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'FR-587-MAR',
        uptime: 99.34,
        region: 'FR-S1',
        cores: 64,
        memory: 128,
        country: 'France',
        latitude: 43.2965,
        longitude: 5.3698,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'ZA-588-CPT',
        uptime: 99.21,
        region: 'ZA-W1',
        cores: 32,
        memory: 64,
        country: 'South Africa',
        latitude: -33.9249,
        longitude: 18.4241,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'IT-589-MIL',
        uptime: 99.45,
        region: 'IT-N1',
        cores: 64,
        memory: 128,
        country: 'Italy',
        latitude: 45.4642,
        longitude: 9.1900,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'ES-590-BCN',
        uptime: 99.67,
        region: 'ES-E2',
        cores: 32,
        memory: 64,
        country: 'Spain',
        latitude: 41.3851,
        longitude: 2.1734,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'MX-591-GDL',
        uptime: 99.03,
        region: 'MX-W1',
        cores: 64,
        memory: 128,
        country: 'Mexico',
        latitude: 20.6597,
        longitude: -103.3496,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'AR-592-COR',
        uptime: 98.89,
        region: 'AR-C1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -31.4201,
        longitude: -64.1888,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'EG-593-ALX',
        uptime: 99.01,
        region: 'EG-N1',
        cores: 64,
        memory: 128,
        country: 'Egypt',
        latitude: 31.2001,
        longitude: 29.9187,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'TR-594-ANK',
        uptime: 99.23,
        region: 'TR-C1',
        cores: 32,
        memory: 64,
        country: 'Turkey',
        latitude: 39.9334,
        longitude: 32.8597,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SA-595-JED',
        uptime: 98.98,
        region: 'SA-W1',
        cores: 64,
        memory: 128,
        country: 'Saudi Arabia',
        latitude: 21.2854,
        longitude: 39.2376,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'IR-596-MSH',
        uptime: 98.87,
        region: 'IR-NE1',
        cores: 32,
        memory: 64,
        country: 'Iran',
        latitude: 36.2605,
        longitude: 59.6168,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SE-597-GOT',
        uptime: 99.76,
        region: 'SE-W1',
        cores: 64,
        memory: 128,
        country: 'Sweden',
        latitude: 57.7089,
        longitude: 11.9746,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'NO-598-BGO',
        uptime: 99.54,
        region: 'NO-W1',
        cores: 32,
        memory: 64,
        country: 'Norway',
        latitude: 60.3913,
        longitude: 5.3221,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'FI-599-TKU',
        uptime: 99.45,
        region: 'FI-S1',
        cores: 64,
        memory: 128,
        country: 'Finland',
        latitude: 60.4518,
        longitude: 22.2666,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'DK-600-AAR',
        uptime: 99.32,
        region: 'DK-E1',
        cores: 32,
        memory: 64,
        country: 'Denmark',
        latitude: 56.1572,
        longitude: 10.2107,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'CH-601-GVA',
        uptime: 99.78,
        region: 'CH-W1',
        cores: 64,
        memory: 128,
        country: 'Switzerland',
        latitude: 46.2044,
        longitude: 6.1432,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'AT-602-GRZ',
        uptime: 99.12,
        region: 'AT-S1',
        cores: 32,
        memory: 64,
        country: 'Austria',
        latitude: 47.0707,
        longitude: 15.4395,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'NZ-603-WLG',
        uptime: 99.56,
        region: 'NZ-N1',
        cores: 64,
        memory: 128,
        country: 'New Zealand',
        latitude: -41.2865,
        longitude: 174.7762,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'TH-604-CNX',
        uptime: 99.23,
        region: 'TH-N1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 18.7883,
        longitude: 98.9853,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'PL-605-WRO',
        uptime: 99.45,
        region: 'PL-SW1',
        cores: 64,
        memory: 128,
        country: 'Poland',
        latitude: 51.1079,
        longitude: 17.0385,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'CZ-606-BRN',
        uptime: 99.01,
        region: 'CZ-SE1',
        cores: 32,
        memory: 64,
        country: 'Czech Republic',
        latitude: 49.1951,
        longitude: 16.6068,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'HU-607-DEB',
        uptime: 99.34,
        region: 'HU-E1',
        cores: 64,
        memory: 128,
        country: 'Hungary',
        latitude: 47.5316,
        longitude: 21.6273,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'RO-608-TIM',
        uptime: 98.98,
        region: 'RO-W1',
        cores: 32,
        memory: 64,
        country: 'Romania',
        latitude: 45.7489,
        longitude: 21.2087,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'BG-609-VAR',
        uptime: 99.12,
        region: 'BG-E1',
        cores: 64,
        memory: 128,
        country: 'Bulgaria',
        latitude: 43.2141,
        longitude: 27.9147,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'RU-610-YEK',
        uptime: 99.67,
        region: 'RU-C1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 56.8389,
        longitude: 60.6057,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'CN-611-CKG',
        uptime: 99.89,
        region: 'CN-SW1',
        cores: 64,
        memory: 128,
        country: 'China',
        latitude: 29.4316,
        longitude: 106.9123,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'RU-612-OMS',
        uptime: 99.23,
        region: 'RU-SB1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 54.9885,
        longitude: 73.3242,
        continent: 'Asia',
      ),
    ];
    _data.addAll([
      const ServerModel(
        serverName: 'US-701-NYC',
        uptime: 99.65,
        region: 'US-E1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 40.7128,
        longitude: -74.0060,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-702-MIA',
        uptime: 99.23,
        region: 'US-SE1',
        cores: 16,
        memory: 32,
        country: 'United States',
        latitude: 25.7617,
        longitude: -80.1918,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-703-DAL',
        uptime: 99.45,
        region: 'US-SW1',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 32.7767,
        longitude: -96.7970,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-704-SEA',
        uptime: 99.78,
        region: 'US-NW1',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 47.6062,
        longitude: -122.3321,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-705-CHI',
        uptime: 99.01,
        region: 'US-C1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 41.8781,
        longitude: -87.6298,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-706-BOS',
        uptime: 99.12,
        region: 'US-NE1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 42.3601,
        longitude: -71.0589,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-707-ATL',
        uptime: 99.23,
        region: 'US-SE2',
        cores: 16,
        memory: 32,
        country: 'United States',
        latitude: 33.7490,
        longitude: -84.3880,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-708-PHX',
        uptime: 99.67,
        region: 'US-SW2',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 33.4484,
        longitude: -112.0740,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'CA-709-MTL',
        uptime: 99.89,
        region: 'CA-E1',
        cores: 128,
        memory: 256,
        country: 'Canada',
        latitude: 45.5017,
        longitude: -73.5673,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'CA-710-VAN',
        uptime: 99.93,
        region: 'CA-W1',
        cores: 64,
        memory: 128,
        country: 'Canada',
        latitude: 49.2827,
        longitude: -123.1207,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'CA-711-EDM',
        uptime: 98.56,
        region: 'CA-W2',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 53.5461,
        longitude: -113.4938,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'MX-712-MEX',
        uptime: 99.67,
        region: 'MX-E1',
        cores: 64,
        memory: 128,
        country: 'Mexico',
        latitude: 19.4326,
        longitude: -99.1332,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'MX-713-MTY',
        uptime: 99.23,
        region: 'MX-N1',
        cores: 32,
        memory: 64,
        country: 'Mexico',
        latitude: 25.6866,
        longitude: -100.3161,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'BR-714-SPA',
        uptime: 99.88,
        region: 'BR-S1',
        cores: 128,
        memory: 256,
        country: 'Brazil',
        latitude: -23.5505,
        longitude: -46.6333,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'BR-715-BH',
        uptime: 99.03,
        region: 'BR-C1',
        cores: 64,
        memory: 128,
        country: 'Brazil',
        latitude: -19.9167,
        longitude: -43.9345,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'AR-716-BUE',
        uptime: 98.76,
        region: 'AR-E1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -34.6037,
        longitude: -58.3816,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'CO-717-BOG',
        uptime: 98.99,
        region: 'CO-C1',
        cores: 32,
        memory: 64,
        country: 'Colombia',
        latitude: 4.7110,
        longitude: -74.0721,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'CL-718-SCL',
        uptime: 99.87,
        region: 'CL-W1',
        cores: 64,
        memory: 128,
        country: 'Chile',
        latitude: -33.4489,
        longitude: -70.6693,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'PE-719-LIM',
        uptime: 98.88,
        region: 'PE-C1',
        cores: 32,
        memory: 64,
        country: 'Peru',
        latitude: -12.0464,
        longitude: -77.0428,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'VE-720-CCS',
        uptime: 98.98,
        region: 'VE-N1',
        cores: 64,
        memory: 128,
        country: 'Venezuela',
        latitude: 10.4806,
        longitude: -66.9036,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'UY-721-MVD',
        uptime: 99.34,
        region: 'UY-S1',
        cores: 32,
        memory: 64,
        country: 'Uruguay',
        latitude: -34.9011,
        longitude: -56.1645,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'US-722-SLC',
        uptime: 99.71,
        region: 'US-NW2',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 40.7608,
        longitude: -111.8910,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-723-HOU',
        uptime: 99.49,
        region: 'US-S1',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 29.7604,
        longitude: -95.3698,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-724-DEN',
        uptime: 99.19,
        region: 'US-C2',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 39.7392,
        longitude: -104.9903,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-725-POR',
        uptime: 99.02,
        region: 'US-NW3',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 45.5122,
        longitude: -122.6587,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-726-MSP',
        uptime: 98.76,
        region: 'US-NC1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 44.9778,
        longitude: -93.2650,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-727-NOR',
        uptime: 99.34,
        region: 'US-SE3',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 36.8508,
        longitude: -76.2859,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-728-SAN',
        uptime: 99.81,
        region: 'US-W2',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 32.7157,
        longitude: -117.1611,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'CA-729-WIN',
        uptime: 99.47,
        region: 'CA-C1',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 49.8951,
        longitude: -97.1384,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-730-ORL',
        uptime: 99.91,
        region: 'US-SE4',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 28.5383,
        longitude: -81.3792,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'BR-731-CWB',
        uptime: 99.78,
        region: 'BR-S2',
        cores: 64,
        memory: 128,
        country: 'Brazil',
        latitude: -25.4284,
        longitude: -49.2733,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'AR-732-SFE',
        uptime: 98.56,
        region: 'AR-C2',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -31.6234,
        longitude: -60.7003,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'CL-733-VAP',
        uptime: 99.34,
        region: 'CL-N1',
        cores: 64,
        memory: 128,
        country: 'Chile',
        latitude: -33.0245,
        longitude: -71.5518,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'US-734-LVS',
        uptime: 99.23,
        region: 'US-W3',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 36.1699,
        longitude: -115.1398,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-735-IND',
        uptime: 98.98,
        region: 'US-MW1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 39.7684,
        longitude: -86.1581,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-736-DET',
        uptime: 99.67,
        region: 'US-NC2',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 42.3314,
        longitude: -83.0458,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-737-CLE',
        uptime: 99.12,
        region: 'US-NC3',
        cores: 64,
        memory: 128,
        country: 'United States',
        latitude: 41.4993,
        longitude: -81.6944,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-738-BUF',
        uptime: 99.87,
        region: 'US-NE2',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 42.8864,
        longitude: -78.8784,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-739-RAL',
        uptime: 99.23,
        region: 'US-SE5',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 35.7796,
        longitude: -78.6382,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'US-740-OMA',
        uptime: 98.67,
        region: 'US-MW2',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 41.2565,
        longitude: -95.9345,
        continent: 'North America',
      ),
    ]);
  }

  List<String> getContinentList() {
    return data.map((e) => e.continent).toSet().toList();
  }

  // find one server data from a continent
  ServerModel findContinentServer(String continent) {
    return data.firstWhere(
      (element) => element.continent == continent,
      orElse: () => ServerModel.empty(),
    );
  }

  List<String> getCountryList() {
    return data.map((e) => e.country).toSet().toList();
  }

  // find country based markers
  List<ServerModel> findCountry(String country) {
    return data.where((element) => element.country == country).toList();
  }

  List<String> getRegionList() {
    return data.map((e) => e.region).toSet().toList();
  }

  // find region based markers
  List<ServerModel> findRegion(String region) {
    return data.where((element) => element.region == region).toList();
  }

  // find countries in a continent
  List<String> findCountryInContinent(String continent) {
    return data
        .where((element) => element.continent == continent)
        .map((e) => e.country)
        .toSet()
        .toList();
  }
}
