import 'package:flutter/foundation.dart';

import 'package:nexqloud/features/main/models/server_model.dart';

class ServerDataProvider with ChangeNotifier {
  List<ServerModel> _data = <ServerModel>[];

  List<ServerModel> get data => _data;

  void setData() {
    _data = <ServerModel>[
      const ServerModel(
        serverName: 'NXQ-842-EEV',
        uptime: 99.87,
        region: 'US-E1',
        cores: 32,
        memory: 64,
        country: 'United States',
        latitude: 37.7749,
        longitude: -122.4194,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'BRZ-452-QZA',
        uptime: 98.76,
        region: 'BR-E1',
        cores: 16,
        memory: 32,
        country: 'Brazil',
        latitude: -14.235004,
        longitude: -51.92528,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'RUS-576-NVS',
        uptime: 99.85,
        region: 'RU-E1',
        cores: 64,
        memory: 128,
        country: 'Russia',
        latitude: 55.755826,
        longitude: 37.6173,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'US-577-LAX',
        uptime: 99.91,
        region: 'US-W1',
        cores: 128,
        memory: 256,
        country: 'United States',
        latitude: 34.0522,
        longitude: -118.2437,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'BR-578-RIO',
        uptime: 99.23,
        region: 'BR-S1',
        cores: 32,
        memory: 64,
        country: 'Brazil',
        latitude: -22.9068,
        longitude: -43.1729,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'DE-579-BER',
        uptime: 99.78,
        region: 'DE-N1',
        cores: 64,
        memory: 128,
        country: 'Germany',
        latitude: 52.5200,
        longitude: 13.4050,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'AU-580-SYD',
        uptime: 99.67,
        region: 'AU-E2',
        cores: 16,
        memory: 32,
        country: 'Australia',
        latitude: -33.8688,
        longitude: 151.2093,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'IN-581-MUM',
        uptime: 99.05,
        region: 'IN-W1',
        cores: 64,
        memory: 128,
        country: 'India',
        latitude: 19.0760,
        longitude: 72.8777,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'RU-582-SPB',
        uptime: 99.45,
        region: 'RU-W1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 59.9343,
        longitude: 30.3351,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'UK-583-MAN',
        uptime: 99.56,
        region: 'UK-N1',
        cores: 64,
        memory: 128,
        country: 'United Kingdom',
        latitude: 53.4808,
        longitude: -2.2426,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'CN-584-SHA',
        uptime: 99.93,
        region: 'CN-E2',
        cores: 128,
        memory: 256,
        country: 'China',
        latitude: 31.2304,
        longitude: 121.4737,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'JP-585-OSA',
        uptime: 99.81,
        region: 'JP-W1',
        cores: 64,
        memory: 128,
        country: 'Japan',
        latitude: 34.6937,
        longitude: 135.5023,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'CA-586-TOR',
        uptime: 99.11,
        region: 'CA-E2',
        cores: 32,
        memory: 64,
        country: 'Canada',
        latitude: 43.6532,
        longitude: -79.3832,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'FR-587-MAR',
        uptime: 99.34,
        region: 'FR-S1',
        cores: 64,
        memory: 128,
        country: 'France',
        latitude: 43.2965,
        longitude: 5.3698,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'ZA-588-CPT',
        uptime: 99.21,
        region: 'ZA-W1',
        cores: 32,
        memory: 64,
        country: 'South Africa',
        latitude: -33.9249,
        longitude: 18.4241,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'IT-589-MIL',
        uptime: 99.45,
        region: 'IT-N1',
        cores: 64,
        memory: 128,
        country: 'Italy',
        latitude: 45.4642,
        longitude: 9.1900,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'ES-590-BCN',
        uptime: 99.67,
        region: 'ES-E2',
        cores: 32,
        memory: 64,
        country: 'Spain',
        latitude: 41.3851,
        longitude: 2.1734,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'MX-591-GDL',
        uptime: 99.03,
        region: 'MX-W1',
        cores: 64,
        memory: 128,
        country: 'Mexico',
        latitude: 20.6597,
        longitude: -103.3496,
        continent: 'North America',
      ),
      const ServerModel(
        serverName: 'AR-592-COR',
        uptime: 98.89,
        region: 'AR-C1',
        cores: 32,
        memory: 64,
        country: 'Argentina',
        latitude: -31.4201,
        longitude: -64.1888,
        continent: 'South America',
      ),
      const ServerModel(
        serverName: 'EG-593-ALX',
        uptime: 99.01,
        region: 'EG-N1',
        cores: 64,
        memory: 128,
        country: 'Egypt',
        latitude: 31.2001,
        longitude: 29.9187,
        continent: 'Africa',
      ),
      const ServerModel(
        serverName: 'TR-594-ANK',
        uptime: 99.23,
        region: 'TR-C1',
        cores: 32,
        memory: 64,
        country: 'Turkey',
        latitude: 39.9334,
        longitude: 32.8597,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SA-595-JED',
        uptime: 98.98,
        region: 'SA-W1',
        cores: 64,
        memory: 128,
        country: 'Saudi Arabia',
        latitude: 21.2854,
        longitude: 39.2376,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'IR-596-MSH',
        uptime: 98.87,
        region: 'IR-NE1',
        cores: 32,
        memory: 64,
        country: 'Iran',
        latitude: 36.2605,
        longitude: 59.6168,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'SE-597-GOT',
        uptime: 99.76,
        region: 'SE-W1',
        cores: 64,
        memory: 128,
        country: 'Sweden',
        latitude: 57.7089,
        longitude: 11.9746,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'NO-598-BGO',
        uptime: 99.54,
        region: 'NO-W1',
        cores: 32,
        memory: 64,
        country: 'Norway',
        latitude: 60.3913,
        longitude: 5.3221,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'FI-599-TKU',
        uptime: 99.45,
        region: 'FI-S1',
        cores: 64,
        memory: 128,
        country: 'Finland',
        latitude: 60.4518,
        longitude: 22.2666,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'DK-600-AAR',
        uptime: 99.32,
        region: 'DK-E1',
        cores: 32,
        memory: 64,
        country: 'Denmark',
        latitude: 56.1572,
        longitude: 10.2107,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'CH-601-GVA',
        uptime: 99.78,
        region: 'CH-W1',
        cores: 64,
        memory: 128,
        country: 'Switzerland',
        latitude: 46.2044,
        longitude: 6.1432,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'AT-602-GRZ',
        uptime: 99.12,
        region: 'AT-S1',
        cores: 32,
        memory: 64,
        country: 'Austria',
        latitude: 47.0707,
        longitude: 15.4395,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'NZ-603-WLG',
        uptime: 99.56,
        region: 'NZ-N1',
        cores: 64,
        memory: 128,
        country: 'New Zealand',
        latitude: -41.2865,
        longitude: 174.7762,
        continent: 'Oceania',
      ),
      const ServerModel(
        serverName: 'TH-604-CNX',
        uptime: 99.23,
        region: 'TH-N1',
        cores: 32,
        memory: 64,
        country: 'Thailand',
        latitude: 18.7883,
        longitude: 98.9853,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'PL-605-WRO',
        uptime: 99.45,
        region: 'PL-SW1',
        cores: 64,
        memory: 128,
        country: 'Poland',
        latitude: 51.1079,
        longitude: 17.0385,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'CZ-606-BRN',
        uptime: 99.01,
        region: 'CZ-SE1',
        cores: 32,
        memory: 64,
        country: 'Czech Republic',
        latitude: 49.1951,
        longitude: 16.6068,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'HU-607-DEB',
        uptime: 99.34,
        region: 'HU-E1',
        cores: 64,
        memory: 128,
        country: 'Hungary',
        latitude: 47.5316,
        longitude: 21.6273,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'RO-608-TIM',
        uptime: 98.98,
        region: 'RO-W1',
        cores: 32,
        memory: 64,
        country: 'Romania',
        latitude: 45.7489,
        longitude: 21.2087,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'BG-609-VAR',
        uptime: 99.12,
        region: 'BG-E1',
        cores: 64,
        memory: 128,
        country: 'Bulgaria',
        latitude: 43.2141,
        longitude: 27.9147,
        continent: 'Europe',
      ),
      const ServerModel(
        serverName: 'RU-610-YEK',
        uptime: 99.67,
        region: 'RU-C1',
        cores: 128,
        memory: 256,
        country: 'Russia',
        latitude: 56.8389,
        longitude: 60.6057,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'CN-611-CKG',
        uptime: 99.89,
        region: 'CN-SW1',
        cores: 64,
        memory: 128,
        country: 'China',
        latitude: 29.4316,
        longitude: 106.9123,
        continent: 'Asia',
      ),
      const ServerModel(
        serverName: 'RU-612-OMS',
        uptime: 99.23,
        region: 'RU-SB1',
        cores: 32,
        memory: 64,
        country: 'Russia',
        latitude: 54.9885,
        longitude: 73.3242,
        continent: 'Asia',
      ),
    ];
  }

  List<String> getContinentList() {
    return data.map((e) => e.continent).toSet().toList();
  }

  // find one server data from a continent
  ServerModel findContinentServer(String continent) {
    return data.firstWhere(
      (element) => element.continent == continent,
      orElse: () => ServerModel.empty(),
    );
  }

  List<String> getCountryList() {
    return data.map((e) => e.country).toSet().toList();
  }

  // find country based markers
  List<ServerModel> findCountry(String country) {
    return data.where((element) => element.country == country).toList();
  }

  List<String> getRegionList() {
    return data.map((e) => e.region).toSet().toList();
  }

  // find region based markers
  List<ServerModel> findRegion(String region) {
    return data.where((element) => element.region == region).toList();
  }

  // find countries in a continent
  List<String> findCountryInContinent(String continent) {
    return data
        .where((element) => element.continent == continent)
        .map((e) => e.country)
        .toSet()
        .toList();
  }
}
