name: nexqloud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^6.7.0
  flutter:
    sdk: flutter
  glassmorphism: ^3.0.0
  go_router: ^14.3.0
  path: ^1.9.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1
  flutter_glow: ^0.3.2
  flutter_inset_box_shadow: ^1.0.8
  syncfusion_flutter_maps: ^27.1.51
  syncfusion_flutter_gauges: ^27.1.51
  fl_chart: ^0.69.0
  syncfusion_flutter_core: ^27.1.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  yaml: any
flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/icons/png/
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/rubik/
    - assets/json/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
        - asset: assets/fonts/rubik/Rubik-Light.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf