name: nexqloud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^6.7.0
  flutter:
    sdk: flutter
  glassmorphism: ^3.0.0
  go_router: ^14.3.0
  path: ^1.9.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  yaml: any
flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/fonts/rubik/